name: CHIMERA CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [clang]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Clang on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y clang-15
          echo "CC=clang-15" >> $GITHUB_ENV
          echo "CXX=clang++-15" >> $GITHUB_ENV

      - name: Setup Clang on macOS
        if: matrix.os == 'macos-latest'
        run: |
          # Homebrew is typically used on macOS runners for package management
          # but clang is usually pre-installed. We just set the variables.
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Verify Compiler
        run: |
          echo "Using C compiler: $($CC --version)"
          echo "Using C++ compiler: $($CXX --version)"

      - name: Install libsodium
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get install -y libsodium-dev
          else
            brew install libsodium
          fi

      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                   -DCMAKE_C_COMPILER=$CC \
                   -DCMAKE_CXX_COMPILER=$CXX

      - name: Build
        run: |
          cd build
          # Use VERBOSE=1 to see the exact compiler commands being used for easier debugging
          make -j$(nproc) VERBOSE=1

      - name: Run tests
        run: |
          cd build
          ./chimera_test
